"""
PDF Report Generation
"""
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT
from django.http import HttpResponse
from datetime import datetime
from io import BytesIO


class PDFReportGenerator:
    """PDF report generation utility"""
    
    @staticmethod
    def generate_books_report(queryset, filename="books_report.pdf"):
        """
        Generate PDF report with books list
        
        Args:
            queryset: Book queryset
            filename: Output filename
            
        Returns:
            HttpResponse with PDF file
        """
        # Create response
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        
        # Create PDF
        doc = SimpleDocTemplate(response, pagesize=letter)
        story = []
        styles = getSampleStyleSheet()
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#366092'),
            spaceAfter=30,
            alignment=TA_CENTER
        )
        title = Paragraph("Library Books Report", title_style)
        story.append(title)
        
        # Subtitle
        subtitle_style = ParagraphStyle(
            'Subtitle',
            parent=styles['Normal'],
            fontSize=12,
            textColor=colors.grey,
            alignment=TA_CENTER,
            spaceAfter=20
        )
        subtitle = Paragraph(f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')}", subtitle_style)
        story.append(subtitle)
        story.append(Spacer(1, 0.3*inch))
        
        # Books table
        data = [['Title', 'Author', 'Price', 'Stock']]
        
        for book in queryset.select_related('author')[:50]:  # Limit to 50 for PDF
            author_name = book.author.name if book.author else 'N/A'
            data.append([
                book.title[:40],  # Truncate long titles
                author_name[:25],
                f'${book.price:.2f}',
                str(book.stock)
            ])
        
        # Create table
        table = Table(data, colWidths=[3.5*inch, 2*inch, 1*inch, 0.8*inch])
        table.setStyle(TableStyle([
            # Header
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#366092')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            
            # Data
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
            ('ALIGN', (0, 1), (0, -1), 'LEFT'),
            ('ALIGN', (2, 1), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('TOPPADDING', (0, 1), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
            
            # Grid
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
        ]))
        
        story.append(table)
        story.append(Spacer(1, 0.3*inch))
        
        # Footer
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=9,
            textColor=colors.grey,
            alignment=TA_CENTER
        )
        footer = Paragraph(
            f"Total Books: {queryset.count()} | Report generated by Library Management System",
            footer_style
        )
        story.append(footer)
        
        # Build PDF
        doc.build(story)
        return response
    
    @staticmethod
    def generate_book_detail_report(book, filename=None):
        """
        Generate detailed PDF report for a single book
        
        Args:
            book: Book instance
            filename: Output filename
            
        Returns:
            HttpResponse with PDF file
        """
        if not filename:
            filename = f"book_{book.id}_report.pdf"
        
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        
        doc = SimpleDocTemplate(response, pagesize=A4)
        story = []
        styles = getSampleStyleSheet()
        
        # Title
        title = Paragraph(f"<b>{book.title}</b>", styles['Title'])
        story.append(title)
        story.append(Spacer(1, 0.2*inch))
        
        # Book details
        details_data = [
            ['Field', 'Value'],
            ['Author', book.author.name if book.author else 'N/A'],
            ['ISBN', book.isbn_number],
            ['Price', f'${book.price:.2f}'],
            ['Stock', str(book.stock)],
            ['Pages', str(book.pages)],
            ['Language', book.language],
            ['Published', book.published_date.strftime('%Y-%m-%d') if book.published_date else 'N/A'],
            ['Genres', ', '.join([g.name for g in book.genres.all()]) or 'N/A'],
        ]
        
        details_table = Table(details_data, colWidths=[2*inch, 4*inch])
        details_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ]))
        
        story.append(details_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Description
        if book.description:
            desc_title = Paragraph("<b>Description:</b>", styles['Heading3'])
            story.append(desc_title)
            desc = Paragraph(book.description, styles['Normal'])
            story.append(desc)
        
        # Build
        doc.build(story)
        return response
    
    @staticmethod
    def generate_invoice(borrow_history, filename=None):
        """
        Generate invoice PDF for book borrowing
        
        Args:
            borrow_history: BorrowHistory instance
            filename: Output filename
            
        Returns:
            HttpResponse with PDF file
        """
        if not filename:
            filename = f"invoice_{borrow_history.id}.pdf"
        
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        
        doc = SimpleDocTemplate(response, pagesize=A4)
        story = []
        styles = getSampleStyleSheet()
        
        # Header
        header = Paragraph("LIBRARY INVOICE", styles['Title'])
        story.append(header)
        story.append(Spacer(1, 0.3*inch))
        
        # Invoice details
        invoice_data = [
            ['Invoice #:', f'INV-{borrow_history.id}'],
            ['Date:', borrow_history.borrowed_at.strftime('%Y-%m-%d')],
            ['Due Date:', borrow_history.due_date.strftime('%Y-%m-%d')],
            ['', ''],
            ['Borrower:', borrow_history.user.get_full_name() or borrow_history.user.username],
            ['Email:', borrow_history.user.email],
        ]
        
        invoice_table = Table(invoice_data, colWidths=[2*inch, 4*inch])
        invoice_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
        ]))
        
        story.append(invoice_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Items
        items_data = [
            ['Book Title', 'Borrow Fee'],
            [borrow_history.book.title, '$5.00'],
            ['', ''],
            ['Total:', '$5.00'],
        ]
        
        items_table = Table(items_data, colWidths=[5*inch, 1.5*inch])
        items_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -2), 1, colors.black),
            ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('LINEABOVE', (0, -1), (-1, -1), 2, colors.black),
        ]))
        
        story.append(items_table)
        story.append(Spacer(1, 0.5*inch))
        
        # Footer
        footer = Paragraph(
            "Thank you for using our library services!",
            styles['Normal']
        )
        story.append(footer)
        
        doc.build(story)
        return response