# Generated by Django 5.2.8 on 2025-11-22 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="available_copies",
            field=models.IntegerField(
                default=5, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
