# Generated by Django 5.2.9 on 2025-12-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="read_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="O'qilgan vaqt"
            ),
        ),
    ]
