# Generated by Django 5.2.8 on 2025-12-02 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_book_cover_image_book_cover_thumbnail_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["title"], name="book_title_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["published_date"], name="book_pub_date_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["available_copies"], name="book_avail_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["author", "published_date"], name="book_author_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["-published_date"], name="book_date_desc_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["-created_at"], name="book_created_desc_idx"),
        ),
    ]
