"""
Django settings for library_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import sys
from decouple import config, Csv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# === SECURITY SETTINGS ===
SECRET_KEY = config("SECRET_KEY")



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())


# Application definition

INSTALLED_APPS = [
    "django.contrib.sites", # New for allauth
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party apps
    "rest_framework",
    "drf_spectacular",
    'rest_framework.authtoken',
    "rest_framework_simplejwt",
    'dj_rest_auth',
    'allauth',
    'allauth.account',
    "allauth.socialaccount",
    'dj_rest_auth.registration',
    "corsheaders",
    "django_filters",
    "debug_toolbar",

    # Local apps
    "books.apps.BooksConfig",
    "accounts.apps.AccountsConfig",
    "emails.apps.EmailsConfig",
    "notifications.apps.NotificationsConfig",
]

# REST FRAMEWORK SETTINGS
# https://www.django-rest-framework.org/api-guide/settings/
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    # YANGI: Default filter backends
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [] if 'test' in sys.argv else [
        'books.throttling.MembershipThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {} if 'test' in sys.argv else {
        'membership': '100/hour',
        'borrow': '5/day',
        'monitored_books': '100/hour',
        'search': '50/hour',
    },
    
    # ========================================
    # API VERSIONING CONFIGURATION
    # ========================================
    'DEFAULT_VERSIONING_CLASS': None,
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1', 'v2'],
    'VERSION_PARAM': 'version',
    
    # ========================================
    # PAGINATION (V2 uchun)
    # ========================================
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,

    # ============================================
    # EXCEPTION HANDLER CONFIGURATION
    # ============================================

    # Custom exception handler
    'EXCEPTION_HANDLER': 'library_project.exception_handler.custom_exception_handler',
}

# SPECTACULAR_SETTINGS
# https://drf-spectacular.readthedocs.io/en/latest/settings.html
SPECTACULAR_SETTINGS = {
    'TITLE': 'Library API',
    'DESCRIPTION': 'Complete REST API for Library Management System',
    'VERSION': '2.0.0',  # ← 2.0.0 ga o'zgartirdik
    'SERVE_INCLUDE_SCHEMA': False,
    
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
    },
    
    'COMPONENT_SPLIT_REQUEST': True,
    
    # ========================================
    # API VERSIONING in Documentation
    # ========================================
    'SERVERS': [
        {'url': 'http://127.0.0.1:8000/api/v1/', 'description': 'V1 API (Deprecated)'},
        {'url': 'http://127.0.0.1:8000/api/v2/', 'description': 'V2 API (Current)'},
    ],
    'TAGS': [
        {'name': 'v1', 'description': 'Version 1 Endpoints (Deprecated)'},
        {'name': 'v2', 'description': 'Version 2 Endpoints (Current)'},
    ],
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # allauth uchun middleware
    "allauth.account.middleware.AccountMiddleware",
    # CUSTOM API VERSIONING MIDDLEWARE
    'books.middleware.APIVersionDeprecationMiddleware',
    'books.middleware.APIVersionMetricsMiddleware', 
    'books.middleware.SentryUserContextMiddleware',
]

# === URLS ===
ROOT_URLCONF = "library_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# === WSGI ===
WSGI_APPLICATION = "library_project.wsgi.application"


# === DATABASE ===
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / config("DB_NAME", default="db.sqlite3"),
    }
}

# === PASSWORD VALIDATION ===
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# === INTERNATIONALIZATION ===
LANGUAGE_CODE = config('LANGUAGE_CODE', default='en-us')
TIME_ZONE = config('TIME_ZONE', default='UTC')
USE_I18N = True
USE_TZ = True

# === STATIC FILES ===
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# === MEDIA FILES Configuration ===
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File upload limits
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880 
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  

# === DEFAULT PRIMARY KEY FIELD TYPE ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# === CACHE SETTINGS (Password Reset uchun) ===
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#         'LOCATION': 'unique-snowflake',
#     }
# }

# === JWT SETTINGS ===
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),     # 30 daqiqa
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),        # 1 kun
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# === SESSION SETTINGS ===
SESSION_COOKIE_AGE = 86400  # 24 hours (seconds)
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_NAME = 'library_sessionid'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # Production'da True qiling

# === SITE ID for django-allauth ===
SITE_ID = 1

# === CACHE CONFIGURATION ===
if DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': 'redis://127.0.0.1:6379/1',
            'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'PARSER_CLASS': 'redis.connection.HiredisParser',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
        },
        'KEY_PREFIX': 'library',
        'TIMEOUT': 300,  # 5 daqiqa (default)
        }
    }


INTERNAL_IPS = ['127.0.0.1']

# Session cache
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'


# CORS CONFIGURATION 
# Debug mode
# CORS Settings
if DEBUG:
    # ========================================
    # DEVELOPMENT SETTINGS
    # ========================================
    print("Development mode: CORS_ALLOW_ALL_ORIGINS = True")
    
    # Barcha origin'larni ruxsat berish (development only!)
    CORS_ALLOW_ALL_ORIGINS = True
    
    # Credentials support
    CORS_ALLOW_CREDENTIALS = True
    
else:
    # ========================================
    # PRODUCTION SETTINGS
    # ========================================
    print("Production mode: Using CORS_ALLOWED_ORIGINS")
    
    # Environment variable'dan o'qish
    cors_origins_str = os.getenv('CORS_ALLOWED_ORIGINS', '')
    
    if cors_origins_str:
        CORS_ALLOWED_ORIGINS = [
            origin.strip() 
            for origin in cors_origins_str.split(',') 
            if origin.strip()
        ]
    else:
        # Default production origins
        CORS_ALLOWED_ORIGINS = [
            "https://yourdomain.com",
            "https://www.yourdomain.com",
            "https://app.yourdomain.com",
        ]
    
    # Credentials
    CORS_ALLOW_CREDENTIALS = True


# ==========================================
# CORS - Common Settings (Dev va Prod uchun)
# ==========================================

# Ruxsat berilgan HTTP methodlar
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Ruxsat berilgan request headerlar
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Frontend'da ko'rinadigan response headerlar
CORS_EXPOSE_HEADERS = [
    'Content-Length',
    'X-Total-Count',
    'X-Page-Number',
]

# Preflight response cache duration (24 soat)
CORS_PREFLIGHT_MAX_AGE = 86400


# ==========================================
# OPTIONAL: Localhost regex pattern (dev uchun)
# ==========================================

# Agar specific localhost portlari kerak bo'lsa:
# CORS_ALLOWED_ORIGIN_REGEXES = [
#     r"^http://localhost:\d+$",       # localhost:any_port
#     r"^http://127\.0\.0\.1:\d+$",    # 127.0.0.1:any_port
# ]

# DEPRECATION SETTINGS AND API VERSIONING
from datetime import datetime

# V1 Sunset Date
V1_SUNSET_DATE = datetime(2025, 12, 31)  # V1 will be sunset on Dec 31, 2025

# API Version Info
API_VERSIONS = {
    'v1': {
        'status': 'deprecated',
        'release_date': '2023-01-15',
        'sunset_date': '2025-12-31',
        'migration_guide': 'https://docs.example.com/api/v1-to-v2',
    },
    'v2': {
        'status': 'active',
        'release_date': '2024-01-15',
        'sunset_date': None,
        'migration_guide': None,
    },
}

# ============================================
# LOGGING CONFIGURATION
# ============================================

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    # ========================================
    # FORMATTERS
    # ========================================
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'detailed': {
            'format': '[{levelname}] {asctime} - {name} - {funcName}:{lineno} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    
    # ========================================
    # FILTERS
    # ========================================
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    
    # ========================================
    # HANDLERS
    # ========================================
    'handlers': {
        # Console output (only in DEBUG mode)
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        
        # General application log
        'file_app': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'app.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        
        # Error log (ERROR and CRITICAL only)
        'file_errors': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
            'formatter': 'detailed',
        },
        
        # API request/response log
        'file_api': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'api.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        
        # Daily rotating log
        'file_daily': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOGS_DIR / 'daily.log',
            'when': 'midnight',
            'interval': 1,
            'backupCount': 30,  # Keep 30 days
            'formatter': 'verbose',
        },
        
        # Email for critical errors (Production only)
        'mail_admins': {
            'level': 'CRITICAL',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'detailed',
        },
    },
    
    # ========================================
    # LOGGERS
    # ========================================
    'loggers': {
        # Django core logging
        'django': {
            'handlers': ['console', 'file_app', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Django request logging (errors only)
        'django.request': {
            'handlers': ['file_errors', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        
        # Django database queries (DEBUG only)
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        
        # Books app logging
        'books': {
            'handlers': ['console', 'file_api', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Accounts app logging
        'accounts': {
            'handlers': ['console', 'file_api', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Custom exception handler logging
        'library_project.exception_handler': {
            'handlers': ['console', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    
    # ========================================
    # ROOT LOGGER (fallback)
    # ========================================
    'root': {
        'handlers': ['console', 'file_app', 'file_errors'],
        'level': 'INFO',
    },
}

# ============================================
# SENTRY CONFIGURATION (Error Tracking)
# ============================================

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
import logging


# STEP 1: Define function FIRST (before using it)
def sentry_before_send(event, hint):
    """
    Filter sensitive data before sending to Sentry
    """
    # Remove password from request data
    if 'request' in event and 'data' in event['request']:
        data = event['request']['data']
        if isinstance(data, dict):
            # Filter password fields
            sensitive_fields = ['password', 'token', 'api_key', 'secret']
            for field in sensitive_fields:
                if field in data:
                    data[field] = '[Filtered]'
    
    # Remove sensitive headers
    if 'headers' in event.get('request', {}):
        headers = event['request']['headers']
        sensitive_headers = ['Authorization', 'Cookie', 'X-API-Key']
        for header in sensitive_headers:
            if header in headers:
                headers[header] = '[Filtered]'
    
    return event


# STEP 2: Now use the function (it's defined above)
SENTRY_DSN = config('SENTRY_DSN', default=None)

if SENTRY_DSN:
    # Logging integration
    sentry_logging = LoggingIntegration(
        level=logging.INFO,        # Capture info and above as breadcrumbs
        event_level=logging.ERROR  # Send errors as events
    )
    
    # Initialize Sentry
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        
        # Integrations
        integrations=[
            DjangoIntegration(),
            sentry_logging,
        ],
        
        # Performance monitoring
        traces_sample_rate=1.0 if DEBUG else 0.1,  # 100% in dev, 10% in prod
        
        # Profiling
        profiles_sample_rate=1.0 if DEBUG else 0.1,
        
        # Send user PII (Personal Identifiable Information)
        send_default_pii=True,
        
        # Environment
        environment=config('ENVIRONMENT', default='development'),
        
        # Release tracking
        release=config('RELEASE_VERSION', default='dev'),
        
        # Before send hook (NOW it works because function is defined above!)
        before_send=sentry_before_send,
        
        # Ignore specific errors
        ignore_errors=[
            KeyboardInterrupt,
            BrokenPipeError,
        ],
    )
    
    print(f"✓ Sentry initialized (Environment: {config('ENVIRONMENT', default='development')})")
else:
    print("⚠ Sentry DSN not configured. Error tracking disabled.")

# ============================================
# EMAIL CONFIGURATION
# ============================================

# Development uchun Console Backend (emaillar terminal'da ko'rinadi)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Production uchun (real email yuborish - keyinroq yoqamiz)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Default email settings
DEFAULT_FROM_EMAIL = 'Library System <noreply@library.com>'
EMAIL_TIMEOUT = 10
EMAIL_USE_LOCALTIME = True

# Site URL for email links
SITE_URL = 'http://localhost:8000'

# Admin emails
ADMINS = [
    ('Admin', 'admin@library.com'),
]
MANAGERS = ADMINS

# ============================================
# FIREBASE PUSH NOTIFICATION (Lesson 30)
# ============================================
FIREBASE_CREDENTIALS_PATH = BASE_DIR / config('FIREBASE_CREDENTIALS_PATH', default='firebase-credentials.json')

# ============================================
# SMS CONFIGURATION (Lesson 30 - MOCK MODE)
# ============================================
SMS_BACKEND = config('SMS_BACKEND', default='mock')  # 'mock' yoki 'twilio'
SMS_ENABLED = config('SMS_ENABLED', default=True, cast=bool)

# Twilio settings (kelajakda kerak bo'lsa)
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER', default='')

# ============================================
# NOTIFICATION SETTINGS (Lesson 30)
# ============================================
NOTIFICATION_SETTINGS = {
    'SMS_ENABLED': SMS_ENABLED,
    'SMS_BACKEND': SMS_BACKEND,
    'PUSH_ENABLED': config('PUSH_ENABLED', default=True, cast=bool),
    'EMAIL_ENABLED': config('EMAIL_ENABLED', default=True, cast=bool),
    'DEFAULT_COUNTRY_CODE': 'UZ',
    'RATE_LIMIT_SMS': '10/hour',
    'RATE_LIMIT_PUSH': '100/hour',
    'MOCK_MODE': SMS_BACKEND == 'mock',  # Mock mode flag
}