# Generated by Django 5.2.9 on 2025-12-24 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Email Bildirishnomalar"
                    ),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(
                        default=True, verbose_name="SMS Bildirishnomalar"
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Push Bildirishnomalar"
                    ),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Belgilangan vaqtda bildirishnoma yuborilmaydi",
                        verbose_name="Sokin Soatlar Yoqilgan",
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="Masalan: 22:00",
                        null=True,
                        verbose_name="Sokin Soatlar Boshlanishi",
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True,
                        help_text="Masalan: 08:00",
                        null=True,
                        verbose_name="Sokin Soatlar Tugashi",
                    ),
                ),
                (
                    "new_book_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Yangi Kitob Bildirishnomalari"
                    ),
                ),
                (
                    "due_date_reminders",
                    models.BooleanField(
                        default=True, verbose_name="Muddat Eslatmalari"
                    ),
                ),
                (
                    "overdue_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Muddati O'tgan Bildirishnomalar"
                    ),
                ),
                (
                    "system_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Tizim Bildirishnomalari"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foydalanuvchi Sozlamalari",
                "verbose_name_plural": "Foydalanuvchi Sozlamalari",
            },
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="FCM Token"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                        ],
                        default="android",
                        max_length=20,
                        verbose_name="Qurilma Turi",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Masalan: iPhone 12, Samsung Galaxy, Chrome Browser",
                        max_length=100,
                        verbose_name="Qurilma Nomi",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Noto'g'ri tokenlar avtomatik o'chiriladi",
                        verbose_name="Faol",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Oxirgi ishlatilgan"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qurilma Token",
                "verbose_name_plural": "Qurilma Tokenlari",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="notificatio_user_id_f0e72c_idx",
                    ),
                    models.Index(fields=["token"], name="notificatio_token_1a2c49_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                        ],
                        max_length=10,
                        verbose_name="Tur",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("sent", "Yuborildi"),
                            ("delivered", "Yetkazildi"),
                            ("failed", "Xatolik"),
                            ("retrying", "Qayta urinilmoqda"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="Holat",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Sarlavha")),
                ("message", models.TextField(verbose_name="Xabar")),
                (
                    "recipient",
                    models.CharField(
                        help_text="Email, telefon raqami yoki qurilma tokeni",
                        max_length=255,
                        verbose_name="Qabul qiluvchi",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yuborilgan vaqt"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yetkazilgan vaqt"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="Xato xabari"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Qo'shimcha ma'lumotlar",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirishnoma Log",
                "verbose_name_plural": "Bildirishnoma Loglari",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["-sent_at"], name="notificatio_sent_at_ab621c_idx"
                    ),
                    models.Index(
                        fields=["user", "-sent_at"],
                        name="notificatio_user_id_7495e7_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "status"],
                        name="notificatio_notific_219496_idx",
                    ),
                ],
            },
        ),
    ]
