# Generated by Django 5.2.9 on 2025-12-04 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_genre_name_book_book_title_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="book",
            name="book_title_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="book_pub_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="book_avail_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="book_author_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="book_date_desc_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="book_created_desc_idx",
        ),
        migrations.RemoveField(
            model_name="book",
            name="available_copies",
        ),
        migrations.RemoveField(
            model_name="book",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="book",
            name="cover_thumbnail",
        ),
        migrations.RemoveField(
            model_name="book",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="book",
            name="published",
        ),
        migrations.RemoveField(
            model_name="book",
            name="publisher",
        ),
        migrations.RemoveField(
            model_name="book",
            name="subtitle",
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="books.author",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="books.genre"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn_number",
            field=models.CharField(db_index=True, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["title", "author"], name="book_title_author_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["isbn_number", "title"], name="book_isbn_title_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["published_date", "author"], name="book_pub_author_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["-created_at", "title"], name="book_created_title_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["price", "title"], name="book_price_title_idx"),
        ),
    ]
