# Generated by Django 5.2.8 on 2025-11-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_available_copies"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Book cover image",
                null=True,
                upload_to="book_covers/",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="cover_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="book_covers/thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
