# Generated by Django 5.2.9 on 2026-01-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="two_factor_method",
            field=models.CharField(
                choices=[("totp", "TOTP"), ("sms", "SMS"), ("none", "None")],
                default="none",
                max_length=10,
            ),
        ),
    ]
