# Generated by Django 5.2.9 on 2025-12-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_options_profile_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="company",
            field=models.CharField(
                blank=True,
                help_text="Company name from GitHub",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Email verified (automatically True for social auth)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="github_url",
            field=models.URLField(
                blank=True, help_text="GitHub profile URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="github_username",
            field=models.CharField(
                blank=True, help_text="GitHub username", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="language",
            field=models.CharField(
                default="en",
                help_text="Preferred language (from Google OAuth)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture_url",
            field=models.URLField(
                blank=True,
                help_text="Profile picture from social providers (Google, GitHub)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True, help_text="Personal website", null=True),
        ),
    ]
